### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by lwxSTCX** [al0ne/Vxscan#18]
我用的python3.7，运行端口跑出来了，操作系统出来了，就自动停止了，怎么回事呢，
![image](https://user-images.githubusercontent.com/43264440/60955574-b82b0f00-a333-11e9-8726-86dc55bd0a2a.png)

**Comment by jojoli123** [comment]
改完后运行结果
oot@kali:~/saomiaoqi/Vxscan# python3 Vxscan.py -u http://www.hhdpharm.com
__     __                         
\ \   / /_  _____  ___ __ _ _ __  
 \ \ / /\ \/ / __|/ __/ _` | '_ \ 
  \ V /  >  <\__ \ (_| (_| | | | |
   \_/  /_/\_\___/\___\__,_|_| |_|
                                  

Start Ping ...
----------------------------------------------------------------------------------------------------
Host: www.hhdpharm.com
----------------------------------------------------------------------------------------------------
GeoIP：
[+] Address: 香港  
[+] Ipaddr: 119.28.7.91
VT PDNS：
[+] None

running 14.652 seconds...
修改前的结果：
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
VT PDNS：
[+] None
PortScan：
[+] Unknown:110
[+] Unknown:80
[+] SMTP:25
Vuln：
[+] Leaks: http://www.opensource.org/licenses/mit-license.php
[+] MySQL SQLi:http://www.hhdpharm.com/en-us/pictures.php?bigclassid=2
[+] MySQL SQLi:http://www.hhdpharm.com/en-us/news.php?classid=2
[+] MySQL SQLi:http://www.hhdpharm.com/news.php?classid=1
[+] MySQL SQLi:http://www.hhdpharm.com/view.php?id=15
[+] MySQL SQLi:http://www.hhdpharm.com/pictures.php?bigclassid=1&smallclassid=4
[+] MySQL SQLi:http://www.hhdpharm.com/message.php?get=view
[+] MySQL SQLi:http://www.hhdpharm.com/en-us/page.php?classid=6
[+] MySQL SQLi:http://www.hhdpharm.com/en-us/view.php?id=97
[+] MySQL SQLi:http://www.hhdpharm.com/en-us/show.php?id=17
[+] MySQL SQLi:http://www.hhdpharm.com/page.php?classid=3
OS：
[+] Actiontec MI424WR-GEN3I WAP

**Comment by lwxSTCX** [comment]
![image](https://user-images.githubusercontent.com/43264440/60958762-7d2bda00-a339-11e9-8ca0-574d451404f1.png)
啥情况啊，。老哥

**Comment by al0ne** [comment]
看看error.log里面的内容

**Comment by lwxSTCX** [comment]
没找到那个文件啊

**Comment by lwxSTCX** [comment]
python3.6 python3.7都试过了，貌似都不行，
