### ISSUE TITLE
ping问题

### ISSUE THREAD

**Issue by jojoli123** [al0ne/Vxscan#20]
如果目标IP禁止ping,那么扫描器将会自动结束任务。
root@kali:~/saomiaoqi/Vxscan# python3 Vxscan.py -u http://www.jxust.cn/
__     __                         
\ \   / /_  _____  ___ __ _ _ __  
 \ \ / /\ \/ / __|/ __/ _` | '_ \ 
  \ V /  >  <\__ \ (_| (_| | | | |
   \_/  /_/\_\___/\___\__,_|_| |_|
                                  

Start Ping ...
218.87.136.6 is not alive

running 2.046 seconds...

**Comment by al0ne** [comment]
setting.py里面有
