### ISSUE TITLE
import socks 出错

### ISSUE THREAD

**Issue by leezp** [al0ne/Vxscan#22]
我下载了 **https://sourceforge.net/projects/socksipy/?source=typ_redirect**  官方 sock.py，放在python3.6 的Lib 文件夹下

运行 python Vxcan.py -u http://127.0.0.1:808/upload-labs-master

运行时报错 

File "E:\software\python3.6\lib\socks.py", line 199
  raise Socks5AuthError,((3,_socks5autherrors[3]))

**Comment by leezp** [comment]
我的环境是win7

**Comment by al0ne** [comment]
pip3 install pysocks
