### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.cli_output'

### ISSUE THREAD

**Issue by songshanyuwu** [al0ne/Vxscan#26]
测试发现报错：ModuleNotFoundError: No module named 'lib.cli_output'
解决的方法：在目录lib下创建空文件__init__.py

分析：每一个包目录下面都会有一个__init__.py的文件，这个文件是必须存在的，否则，Python就把这个目录当成普通目录(文件夹)，而不是一个包。__init__.py可以是空文件，也可以有Python代码，因为__init__.py本身就是一个模块，而它的模块名就是对应包的名字。调用包就是执行包下的__init__.py文件。

=====补充====
树莓派2B+ （单纯的Arm版的Linux系统，基于Debian）+Python 3.7.3
可能我是个例吧，-_-||

**Comment by al0ne** [comment]
Python啥版本 啥系统啊  我一直好好地 没遇到过这种情况

**Comment by tomtang-dev** [comment]
> 测试发现报错：ModuleNotFoundError: No module named 'lib.cli_output'
> 解决的方法：在目录lib下创建空文件__init__.py
> 
> 分析：每一个包目录下面都会有一个__init__.py的文件，这个文件是必须存在的，否则，Python就把这个目录当成普通目录(文件夹)，而不是一个包。**init**.py可以是空文件，也可以有Python代码，因为__init__.py本身就是一个模块，而它的模块名就是对应包的名字。调用包就是执行包下的__init__.py文件。

从python3.x(具体哪个版本忘了)起，包目录不加__init__.py也可以当作包

**Comment by yanghaoi** [comment]
我装了py3.8.2,然后也是这个错误==!（Ubuntu16）

**Comment by xuguozhen** [comment]
各位好，这个问题解决了吗？Python2.7的代码移植到Python3.6，就一直报这个错，有什么建议吗？
