### ISSUE TITLE
安装依赖uvloop是报错，不支持windows，有什么好的解决办法嘛？

### ISSUE THREAD

**Issue by AI0TSec** [al0ne/Vxscan#27]
uvloop does not support Windows at the moment
![image](https://user-images.githubusercontent.com/48520137/68825274-81e01080-06d4-11ea-88ca-a5d7d19bb527.png)

**Comment by al0ne** [comment]
windows 下不安装也可以的 ，我在代码里设置了检测到windows系统就不加载uvloop

```
if platform.system() != 'Windows':
    import uvloop
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
    LIMIT = 800
else:
    LIMIT = 200
```
