### ISSUE TITLE
URLS bug

### ISSUE THREAD

**Issue by AnotherVol** [al0ne/Vxscan#28]
每次扫描到的敏感文件都不一样

**Comment by al0ne** [comment]
额 你至少也贴个图或者扫描结果吧  不然怎么排查呢

**Comment by AnotherVol** [comment]
![image](https://user-images.githubusercontent.com/13464049/72502361-13563500-3874-11ea-8fe8-2c4d52b811a6.png)
![image](https://user-images.githubusercontent.com/13464049/72503107-e7d44a00-3875-11ea-98de-06ff721d9898.png)



不好意思没说清楚 有些敏感文件多，扫出来只是一部分，有时候没有扫出来

**Comment by Axianke** [comment]
import dns.resolver 这个包怎么安装呢？

**Comment by Axianke** [comment]
生成的html空白打开空白文件
