### ISSUE TITLE
Vxscan as a webservice

### ISSUE THREAD

**Issue by ghost** [al0ne/Vxscan#33]
Hi @al0ne  ,

Hope you are all well !

Would it be complicated to create a web-service mode for Vxscan with a celery queue ?

Thanks for any insights or inputs about that.

Cheers,
Luc Michalski

**Comment by al0ne** [comment]
vxscan3 has adopted celery+redis for task scheduling

**Comment by ghost** [comment]
Hi @al0ne ,

Thanks for this quick reply :-) 

Is it possible to add a flask server api ?

Cheers,
Luc

**Comment by al0ne** [comment]
OK I will consider, I am currently reorganizing vxscan architecture

**Comment by ghost** [comment]
awesome, thanks :-)

In fact, my goal is to use vxscan and some other pentest tools in a n8n workflow:
![n8n-screenshot](https://user-images.githubusercontent.com/1963546/103862048-a9efb780-50be-11eb-86d2-0a1ca8d687dd.png)

I definitely recommend n8n, it is neat :-)
