### ISSUE TITLE
拉取不到安装包

### ISSUE THREAD

**Issue by xiaoliu1027** [al0ne/Vxscan#36]
└─# wget https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
--2023-01-31 02:17:17--  https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’

大佬们，这个问题怎么解决呢

**Comment by wlaq-su** [comment]
我也是这个问题

**Comment by al0ne** [comment]
从网上找找这个GeoIP下载地址。
