### ISSUE TITLE
多域名扫描还是有问题

### ISSUE THREAD

**Issue by strengthen8** [al0ne/Vxscan#7]
root@qA-year:~/Vxscan# python3 Vxscan.py -f hosts.txt 
__     __                         
\ \   / /_  _____  ___ __ _ _ __  
 \ \ / /\ \/ / __|/ __/ _` | '_ \ 
  \ V /  >  <\__ \ (_| (_| | | | |
   \_/  /_/\_\___/\___\__,_|_| |_|
                                  

 
PortScan：
[+] http:8080
[+] http:80
[+] http:443
 
Vuln：
[+] django url jump : http://XgXXX:8080
[+] http://XXX.XXX.com:8080 |XXX
[+] https://XXX.XXX.com |XXX
OS：
[+] Linux 3.2 - 3.8

running 162.181 seconds...

**Comment by al0ne** [comment]
是只扫描了这一个域名吗？

**Comment by strengthen8** [comment]
扫描了一个域名列表的txt文本，里面包含了几百个域名吧

**Comment by al0ne** [comment]
error.log里有没有报错信息？  是不是报错中止了？

**Comment by strengthen8** [comment]
Traceback (most recent call last):
  File "Vxscan.py", line 322, in pool
    name, wafresult = start(host)
  File "/root/Vxscan/lib/common.py", line 206, in start
    'Address': address,
UnboundLocalError: local variable 'address' referenced before assignment

**Comment by al0ne** [comment]
多谢  这个应该是遇到了内网地址吧 所有在geoip库里没查找出来  我加个异常处理就行

**Comment by strengthen8** [comment]
嗯 代码什么时候提交上去？
